### ISSUE TITLE
Temperature is rounded

### ISSUE THREAD

**Issue by SHammade** [electrified/asus-wmi-sensors#18]
Hi there,

thanks for your work!
The k10temp module provides me more detailed temperatures, so it seems to me this module round the values?

ITE IT8665E on ASUS PRIME X470-PRO

% sensors
asus-isa-0000
Adapter: ISA adapter
cpu_fan:        0 RPM

asuswmisensors-isa-0000
Adapter: ISA adapter
CPU Core Voltage:         +0.84 V  
+12V Voltage:            +10.08 V  
+5V Voltage:              +4.96 V  
3VSB Voltage:             +3.29 V  
CPU Fan:                  422 RPM
Chassis Fan 1:            886 RPM
Chassis Fan 2:            661 RPM
Chassis Fan 3:              0 RPM
AIO Pump:                   0 RPM
Water Pump:                 0 RPM
CPU OPT:                  512 RPM
CPU Temperature:          +32.0°C  
Motherboard Temperature:  +35.0°C  
Chipset Temperature:      +44.0°C  
Tsensor 1 Temperature:   +216.0°C  

k10temp-pci-00c3
Adapter: PCI adapter
Ryzen 2700 DIE:  +32.4°C  (high = +70.0°C)
Ryzen 2700:      +32.4°C  

% sensors
asus-isa-0000
Adapter: ISA adapter
cpu_fan:        0 RPM

asuswmisensors-isa-0000
Adapter: ISA adapter
CPU Core Voltage:         +0.38 V  
+12V Voltage:            +10.08 V  
+5V Voltage:              +4.99 V  
3VSB Voltage:             +3.29 V  
CPU Fan:                  410 RPM
Chassis Fan 1:            870 RPM
Chassis Fan 2:            653 RPM
Chassis Fan 3:              0 RPM
AIO Pump:                   0 RPM
Water Pump:                 0 RPM
CPU OPT:                  498 RPM
CPU Temperature:          +31.0°C  
Motherboard Temperature:  +35.0°C  
Chipset Temperature:      +44.0°C  
Tsensor 1 Temperature:   +216.0°C  

k10temp-pci-00c3
Adapter: PCI adapter
Ryzen 2700 DIE:  +31.8°C  (high = +70.0°C)
Ryzen 2700:      +31.8°C 

sensors
asus-isa-0000
Adapter: ISA adapter
cpu_fan:        0 RPM

asuswmisensors-isa-0000
Adapter: ISA adapter
CPU Core Voltage:         +0.86 V  
+12V Voltage:            +10.08 V  
+5V Voltage:              +4.96 V  
3VSB Voltage:             +3.29 V  
CPU Fan:                  509 RPM
Chassis Fan 1:            962 RPM
Chassis Fan 2:            725 RPM
Chassis Fan 3:              0 RPM
AIO Pump:                   0 RPM
Water Pump:                 0 RPM
CPU OPT:                  637 RPM
CPU Temperature:          +36.0°C  
Motherboard Temperature:  +34.0°C  
Chipset Temperature:      +44.0°C  
Tsensor 1 Temperature:   +216.0°C  

k10temp-pci-00c3
Adapter: PCI adapter
Ryzen 2700 DIE:  +35.6°C  (high = +70.0°C)
Ryzen 2700:      +35.6°C

**Comment by electrified** [comment]
Hi, there is no rounding of the temperature within the driver, the values read from the ASUS WMI do not have any decimal places.

I am unsure if this is a limitation of the IT8665E or if it's done within the ASUS firmware.

There are no decimal places shown within the UEFI, or in HWiNFO for the same readings:

![190506074025](https://user-images.githubusercontent.com/103082/57212582-16f2a600-6fdc-11e9-8e68-53be08da9865.png)

<img width="560" alt="Capture" src="https://user-images.githubusercontent.com/103082/57212599-21ad3b00-6fdc-11e9-851b-0c3c6e6b51d0.PNG">
