### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by vdub12** [electrified/asus-wmi-sensors#26]
getting the error "fatal error: linux/wmi.h: No such file or directory" when I try and compile. 

Do you know if this will work on the TUF B450M-Plus?

**Comment by electrified** [comment]
Hi, what distribution are you using and what kernel version are you on?

Regarding the TUF B450M-Plus, I think it is unlikely that it has WMI support. 

If you use HWiNFO in Windows does it say it's using ASUS WMI or the ITE chip directly?

**Comment by vdub12** [comment]
It's openSuse Leap 15. Kernel is 4.12.14

**Comment by electrified** [comment]
The WMI interface is not present in 4.12.14, it was introduced in 14.13, hence the error you are getting

https://elixir.bootlin.com/linux/v4.12.14/source/include/linux/wmi.h

vs

https://elixir.bootlin.com/linux/v4.13/source/include/linux/wmi.h

**Comment by vdub12** [comment]
Awe, makes sense. Considering the TUF boards probably don't support WMI
anyway I'll wait until I upgrade Leap and try again.

Next time I'm in Windows I'll check it out. It typically takes a few hours
to reboot because of system lockups due to the it87 driver. I normally have
to reboot about 15+ times because sensors crashes and the fans drop to
their lowest speed and I get hard lockups.

Thanks.

**Comment by electrified** [comment]
OK. I will close this issue for now. If you do find the board uses WMI under Windows open a new ticket and I will add the board ID.
