### ISSUE TITLE
How to autoload it in Ubuntu?

### ISSUE THREAD

**Issue by laichiaheng** [electrified/asus-wmi-sensors#32]
where is the asus-wmi-sensors.conf for `/etc/module-load.d/`

**Comment by KeithMyers** [comment]
? ? All you need is the line "asus-wmi-sensors" in the modules.conf file.

**Comment by ThoreauHenry** [comment]
sudo echo "asus-wmi-sensors" > /etc/modules-load.d/modules.conf
