### ISSUE TITLE
Asus Prime X470-pro mobo fans strange behaviour

### ISSUE THREAD

**Issue by Baszczer** [electrified/asus-wmi-sensors#48]
Hi, 
Is it possible for the module to cause incorrect behavior of the case fans? 
For no apparent reason, one or the other begin to spin at high speed, only turning off the computer helps.
Cpu and gpu fan work properly.
There was no problem when I was using Windows. I changed the settings in the bios, from pwm to dc and nothing helps. 
I am using Ubuntu 18.04 lts

**Comment by electrified** [comment]
Hi there,

Yes this behaviour has been seen before, also in Windows if using AIDA64, HWiNFO or other programs that use the ASUS WMI interface. AI Suite doesn't usually seem to cause the problem.

The problem appears to be with the code running in the EC(Embedded Controller) which can lock up.

All I can suggest is:
1) Try different BIOS versions, both newer and older. 
2) Increase the polling interval of your sensor software - The more often you poll the sensor values, the more likely it seems to happen

See these threads for similar problems:

https://www.reddit.com/r/ASUS/comments/afjpem/strix_x470i_ec_sensorwmi_issues_freezingfan_speeds/

https://rog.asus.com/forum/showthread.php?95367-Temperature-Sensors-failing-Fans-on-Max-speed-problem

https://rog.asus.com/forum/showthread.php?112744-Crosshair-VI-Wifi-fan-control-sensors-are-broken

**Comment by Baszczer** [comment]
Thanks
