### ISSUE TITLE
Support for fan extension card

### ISSUE THREAD

**Issue by phemmer** [electrified/asus-wmi-sensors#5]
First off, thanks for the driver. This is much better than it87.

Is there any possibility for support of the [Asus fan extension card](https://www.asus.com/Motherboard-Accessories/FAN-EXTENSION-CARD/overview/)?

I have the card on my system, and can provide any information needed to investigate the possibility.
Aside from that card, the motherboard I'm using is the ROG Crosshair VII Hero.

Thanks

**Comment by electrified** [comment]
We're at the mercy of what sensors ASUS exposes via the UEFI WMI interface, and it may be they don't supply the extension fan values.

Do you have a Windows install? If so do the fan extension values show up in AI Suite? Can you also try HWiNFO?

I've bought a fan extension board off eBay so hopefully should have one to try soon.

**Comment by phemmer** [comment]
Unfortunately no, I do not have a windows install I can boot into.

**Comment by electrified** [comment]
I've received my fan extension board, and unfortunately the fan speeds/temperatures aren't exposed via ASUS' WMI interface. I checked in Windows, and the extension board sensors do show up in AI Suite 3, but not any software that uses ASUS WMI such as HWiNFO.

I will try getting in contact with ASUS support and asking them to add them to the firmware, but I don't have high hopes that they will do anything.. :D

The fan extension card has a NCT7802Y on it, an I2C device which does have a linux driver (see https://www.spinics.net/lists/linux-hwmon/msg04236.html), so it may be possible to monitor to get support via that route. I also didn't have any success on getting it to work..

As an aside, the fan extension board is reported in the hacked up Zenith Extreme's WMI output (see https://user-images.githubusercontent.com/6266419/51900893-b3425680-23b6-11e9-86c0-0965c0ae5a04.jpg), so it just seems they omitted it on the CH7.

I'm going to close this issue as there is nothing I can do to support it without an ASUS firmware change.
