### ISSUE TITLE
Crosshair VIII x570 / Ryzen 3900

### ISSUE THREAD

**Issue by robschaap242** [electrified/asus-wmi-sensors#51]
Hey there, been trying to get this working with my MB, to no avail. Any chance that support is in the works, or reason that it won't? Thank you

**Comment by electrified** [comment]
Hi,

As the readme says, the sensors WMI interface isn't present in the BIOS of any of Asus' X570 boards so they will never be supported by this driver.

They've used a different hardware monitoring IC though, which should be supported by the  `nct6775` driver.
