### ISSUE TITLE
Asus PRIME X470-PRO, CPU OPT doesn't work, works in UEFI

### ISSUE THREAD

**Issue by j1warren** [electrified/asus-wmi-sensors#54]
`CPU OPT:                    0 RPM`

Although, UEFI shows correct values. Any ideas, what I could try?

**Comment by electrified** [comment]
It's a BIOS issue. See https://www.hwinfo.com/forum/threads/temperatures-after-bios-update-not-shown-anymore-asus-prime-x470-pro.5921/ for the same issue occurring under Windows with HWiNFO

All I can recommend is reporting the issue to Asus.

**Comment by electrified** [comment]
Closing this as there is no resolution I can provide (it's down to ASUS to fix their BIOS)
