### ISSUE TITLE
Failed to build it via AUR.

### ISSUE THREAD

**Issue by laichiaheng** [electrified/asus-wmi-sensors#60]
==> dkms install asus-wmi-sensors/53.b6c25d2 -k 5.5.9-1-MANJARO
Error! Bad return status for module build on kernel: 5.5.9-1-MANJARO (x86_64)

**Comment by electrified** [comment]
Hey.

I have just tested this, and it works OK with the `linux55` kernel, which for me currently gets 5.5.8-1-MANJARO.

Installed from `manjaro-kde-19.0.2-200311-linux54.iso`, updated, installed kernel `linux55`, and `linux55-headers`.

Installed with `pamac build asus-wmi-sensors-dkms-git` and all worked OK.

What is in the DKMS logs?

**Comment by laichiaheng** [comment]
How to check the DKMS logs?
It used to work with 5.5.9 for me, too.

**Comment by laichiaheng** [comment]
It works again after Manjaro release a fix for 5.5.9

**Comment by electrified** [comment]
Glad you have got it sorted :)
