### ISSUE TITLE
Asus Prime TRX40-Pro fails

### ISSUE THREAD

**Issue by kk-1** [electrified/asus-wmi-sensors#70]
Hello,
Tried your module on Asus Prime TRX40-Pro motherboard without success.
Here is some stuff you can utilize.

dmesg:
---------------------------------------------------------
...
asus_wmi_sensors: loading out-of-tree module taints kernel.
asus_wmi_sensors: module verification failed: signature and/or required key missing - tainting kernel
asuswmisensors: Vendor: ASUSTeK COMPUTER INC. Board: PRIME TRX40-PRO BIOS version: 1101 WMI version: 0
asuswmisensors: Unsupported board
...
-------------------------------------------------------------------------

dmidecode -t baseboard:
-----------------------------------------------------------
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 3.2.0 present.

Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
        Manufacturer: ASUSTeK COMPUTER INC.
        Product Name: PRIME TRX40-PRO
        Version: Rev 1.xx
        Serial Number: XXXXXXXXXXXXX
        Asset Tag: Default string
        Features:
                Board is a hosting board
                Board is removable
                Board is replaceable
        Location In Chassis: Default string
        Chassis Handle: 0x0003
        Type: Motherboard
        Contained Object Handles: 0

Handle 0x002C, DMI type 10, 6 bytes
On Board Device Information
        Type: Video
        Status: Enabled
        Description:    To Be Filled By O.E.M.

Handle 0x0032, DMI type 41, 11 bytes
Onboard Device
        Reference Designation:  Onboard IGD
        Type: Video
        Status: Enabled
        Type Instance: 1
        Bus Address: 0000:00:02.0

Handle 0x0033, DMI type 41, 11 bytes
Onboard Device
        Reference Designation:  Onboard LAN
        Type: Ethernet
        Status: Enabled
        Type Instance: 1
        Bus Address: 0000:00:19.0

Handle 0x0034, DMI type 41, 11 bytes
Onboard Device
        Reference Designation:  Onboard 1394
        Type: Other
        Status: Enabled
        Type Instance: 1
        Bus Address: 0000:03:1c.2

-------------------------------------------------------------------------------

Thanks for your effort.

**Comment by electrified** [comment]
Hi.

The Asus Threadripper 3rd gen boards, like the X570 boards don't have the WMI interface.

They do however have the Nuvoton NCT6798D sensor IC which is supported by the mainline nct6775 driver.

`sensors-detect —auto` should be able to find it.
