### ISSUE TITLE
PRIME B350-PLUS

### ISSUE THREAD

**Issue by Chris1512** [electrified/asus-wmi-sensors#76]
According to this link
[https://www.computerbase.de/forum/threads/asus-prime-b350-plus-liest-cpu-temp-falsch-aus.1922786/](url)
the mentioned board should be supported.
The following is the the output you asked for in order to possibly provide support for the board:
`dmidecode -t baseboard
# dmidecode 3.3
Getting SMBIOS data from sysfs.
SMBIOS 3.1.1 present.

Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
	Manufacturer: ASUSTeK COMPUTER INC.
	Product Name: PRIME B350-PLUS
	Version: Rev X.0x
	Serial Number: 171113947804502
	Asset Tag: Default string
	Features:
		Board is a hosting board
		Board is replaceable
	Location In Chassis: Default string
	Chassis Handle: 0x0003
	Type: Motherboard
	Contained Object Handles: 0

Handle 0x001F, DMI type 10, 6 bytes
On Board Device Information
	Type: Video
	Status: Enabled
	Description:    To Be Filled By O.E.M.

Handle 0x0024, DMI type 41, 11 bytes
Onboard Device
	Reference Designation:  Onboard IGD
	Type: Video
	Status: Enabled
	Type Instance: 1
	Bus Address: 0000:00:02.0`

Is it possible to add support?

**Comment by electrified** [comment]
In the hwinfo shots in the thread you link to, it can be seen that HWINFO is accessing the IT8665E chip directly, not via the WMI interface. As far as I know there are no prime x350/x370 boards with the WMI interface in their firmware.

The easiest way to check if your board has the required UEFI interface is as per: https://github.com/electrified/asus-wmi-sensors/issues/11#issuecomment-515903663
