### ISSUE TITLE
It builds but I cannot modprobe the module 

### ISSUE THREAD

**Issue by eduardflorinescu** [electrified/asus-wmi-sensors#82]
I have prime x370 
and breaks when I try to modprobe

`sudo modprobe asus-wmi-sensors`

`modprobe: ERROR: could not insert 'asus_wmi_sensors': Unknown symbol in module, or unknown parameter (see dmesg)
`

`dmesg`

`[ 9409.006845] asus_wmi_sensors: Unknown symbol wmi_evaluate_method (err -2)`
`[ 9409.006865] asus_wmi_sensors: Unknown symbol wmi_has_guid (err -2)`
`[ 9437.164998] asus_wmi_sensors: Unknown symbol wmi_evaluate_method (err -2)`
`[ 9437.165017] asus_wmi_sensors: Unknown symbol wmi_has_guid (err -2)`
`[ 9685.629090] asus_wmi_sensors: Unknown symbol wmi_evaluate_method (err -2)`
`[ 9685.629108] asus_wmi_sensors: Unknown symbol wmi_has_guid (err -2)`
`[ 9765.812363] asus_wmi_sensors: Unknown symbol wmi_evaluate_method (err -2)`
`[ 9765.812384] asus_wmi_sensors: Unknown symbol wmi_has_guid (err -2)`
`[ 9834.682192] asus_wmi_sensors: Unknown symbol wmi_evaluate_method (err -2)`
`[ 9834.682207] asus_wmi_sensors: Unknown symbol wmi_has_guid (err -2)`
`[ 9863.485958] asus_wmi_sensors: Unknown symbol wmi_evaluate_method (err -2)`
`[ 9863.485973] asus_wmi_sensors: Unknown symbol wmi_has_guid (err -2)`
`[ 9905.914430] asus_wmi_sensors: Unknown symbol wmi_evaluate_method (err -2)`
`[ 9905.914449] asus_wmi_sensors: Unknown symbol wmi_has_guid (err -2)`

**Comment by electrified** [comment]
Hi, this suggests that the kernel was built without WMI I believe.

Also, as per the readme, there are no supported X370 boards so this won't work even if you got past the compilation issues.

Finally this driver has been merged into kernel mainline, so I'd recommend using that over this repository.
